### ISSUE TITLE
In Phonegap  lang   always is 'en'

### ISSUE THREAD

**Issue by escolhatecnologia** [matthiasmullie/hotelguide#26]
config.xml

Why lang  always  is "en"

so    lang="fr"

``` xml
    <name xml:lang="fr">Guide d'Hôtels</name>
```

doesnt  work  in  phonegap 
any  solution for translate name app?

@matthiasmullie 

Thanks

**Comment by matthiasmullie** [comment]
Sorry, I have no idea. It's been a couple of years since I've used Phonegap at all, so I'm not even sure how it currently works...
